- includes/class-sensei-course-progress.php
It will be looks like `frontend.css?ver=1.0.6`
It was like this: `frontend.css?ver=f35c6fc4a1a93ff6b4ffa4b9763a7163`
> Correct version of frontend.css file

- includes/class-sensei-course-progress-widget.php
- includes/class-sensei-course-progress.php
- sensei-course-progress.php
Added more escape functions on everything, including translations.
Also loading files using their absolute path.
cc @pgk @danjjohnson 
Note: coding standards are not included in this PR, I'll make changes for those once this is merged, otherwise it will be harder to review the changes made here.
> Escape data and use absolute paths to files

- .editorconfig
- .gitignore
- composer.json
- composer.lock
- phpcs.ruleset.xml
Simple PR to help keep things tidy.
> Adds .editorconfig and PHPCS ruleset

- README.md
Updated the Readme to include a description of the plugin, plus _Getting Started_ and _Contributing_ sections.
> Update ReadMe to include more details

- includes/class-sensei-course-progress-widget.php
I moved most of the implementation from #38 to Sensei core.
See PR #38 for testing instructions.
Sensei core: https://github.com/Automattic/sensei/pull/2061
> Move 'do_link_to_module' method to Sensei core and check for implementation

- changelog.txt
- languages/sensei-course-progress.pot
- sensei-course-progress.php
- Bump version
- Update change log
- Update .pot file
> 1.0.7 Release

- includes/class-sensei-course-progress.php
- sensei-course-progress.php
Small change to #29 for PHP 5.2 compatibility. Introduced in `1.0.7-beta-1`
> Switch `__DIR__` to `dirname( __FILE__)` for PHP 5.2

- includes/class-sensei-course-progress-widget.php
- sensei-course-progress.php
> Update plugin author information

- gulpfile.js
This PR updates the build to:
- Not copy the `vendor` folder to the `build` folder
- Copy `changelog.txt` and `README.md` to the `build` folder
> Update Gulp build

- LICENSE
- README.md
- gulpfile.js
- package-lock.json
- package.json
NOTE: In an effort to make the build and package scripts consistent with the rest of Sensei and extensions, this PR moves the build files from the `build` directory to the `build/sensei-course-progress` directory.
> Add gulp tasks for creating the release package

- assets/css/frontend.scss
Fixes https://github.com/woocommerce/sensei-course-progress/issues/53
To test, switch to this branch, `gulp build`, and follow the instructions in #53 
Also test with the Dive theme, which contains this issue without adding the code snippet mentioned in #53.
> Ensure widget CSS works with custom widget class

- changelog.txt
- languages/sensei-course-progress.pot
- package-lock.json
- package.json
- sensei-course-progress.php
* Update change log
* Bump version number
* Update POT file
> Release 2.0.0 Beta 2

- gulpfile.js
- includes/class-sensei-course-progress.php
- languages/sensei-course-progress.pot
- package-lock.json
- package.json
- Run `gulp build` or `npm run prod` to create a Production-ready version of the plugin with compressed assets.
- Run `NODE_ENV='dev' gulp build` or `npm run dev`  to create a development version with uncompressed assets.
> Improve build process to take advantage of Gulp 4 features

- changelog.txt
- package-lock.json
- sensei-course-progress.php
- Update release date in changelog
- Bump version
- Bump WP version in header
> Release 2.0.0

- composer.json
- composer.lock
- package.json
PR #80 is failing so I'm updating composer and npm packages manually.
> Pin composer and npm dependencies

- README.md
- changelog.txt
- gulpfile.js
- includes/class-sensei-course-progress-dependency-checker.php
- includes/class-sensei-course-progress-widget.php
- phpcs.xml.dist
- readme.txt
- sensei-course-progress.php
This PR renames the plugin to Sensei LMS Course Progress and adds a Read Me file for WordPress.org.
> Rename plugin to Sensei LMS Course Progress

- changelog.txt
- package-lock.json
- package.json
- readme.txt
- sensei-course-progress.php
- Update change log
- Bump version
- Bump WordPress tested version to 5.3
> Release 2.0.1

- languages/sensei-course-progress.pot
- sensei-course-progress.php
- Update pot file
- Bump minimum required WordPress version to 4.9 to align with what Sensei LMS uses
- Bump WordPress tested version to 5.3
> Update pot file and WordPress versions

- changelog.txt
- package-lock.json
- package.json
- readme.txt
- sensei-course-progress.php
- Update change log
- Bump version
> Release 2.0.2

- readme.txt
- sensei-course-progress.php
* Tested the plugin with WP 5.7 and updated version.
> Update tested version to 5.7
